# Generated by Django 6.0.1 on 2026-02-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convocatoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(help_text='Descripción general de la convocatoria')),
                ('dependencia', models.CharField(help_text='Dependencia o dirección que convoca', max_length=200)),
                ('objetivo', models.TextField(help_text='Objetivo del programa')),
                ('dirigido_a', models.TextField(help_text='A quién va dirigida la convocatoria')),
                ('requisitos', models.TextField(help_text='Requisitos generales')),
                ('beneficios', models.TextField(help_text='Beneficios que ofrece el programa')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(help_text='Fecha límite para recibir documentos')),
                ('lugar_recepcion', models.CharField(help_text='Lugar donde se reciben los documentos', max_length=255)),
                ('horario', models.CharField(help_text='Horario de atención', max_length=100)),
                ('forma_entrega', models.CharField(help_text='Forma de entrega de documentos', max_length=200)),
                ('contacto', models.TextField(help_text='Teléfono, correo o redes oficiales')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='convocatorias/')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
