# Generated by Django 6.0.1 on 2026-02-06 10:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='convocatoria',
            name='cupo_maximo',
            field=models.PositiveIntegerField(default=0, help_text='0 = sin límite de inscripciones'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('cancelada', 'Cancelada')], default='activa', max_length=20)),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_registro', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('nota_admin', models.TextField(blank=True)),
                ('convocatoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='convocatorias.convocatoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inscripciones_convocatoria', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['convocatoria', 'estado'], name='convocatori_convoca_81c79e_idx'), models.Index(fields=['usuario', 'estado'], name='convocatori_usuario_fc0a5e_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('estado', 'activa')), fields=('convocatoria', 'usuario'), name='uniq_inscripcion_activa_por_usuario')],
            },
        ),
    ]
