# Generated by Django 6.0.1 on 2026-02-13 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convocatorias", "0002_convocatoria_cupo_maximo_inscripcion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PerfilUsuario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre_completo", models.CharField(max_length=255)),
                ("curp", models.CharField(max_length=18)),
                ("telefono", models.CharField(max_length=20)),
                ("direccion", models.CharField(max_length=255)),
                ("fecha_actualizacion", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="perfil_usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoUsuario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("identificacion_oficial", "Identificacion oficial"),
                            ("curp", "CURP"),
                            ("comprobante_domicilio", "Comprobante de domicilio"),
                        ],
                        max_length=40,
                    ),
                ),
                ("archivo", models.FileField(upload_to="documentos_usuarios/%Y/%m/%d")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("en_revision", "En revision"),
                            ("aceptado", "Aceptado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="en_revision",
                        max_length=20,
                    ),
                ),
                ("fecha_carga", models.DateTimeField(auto_now=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("usuario", "tipo"),
                        name="uniq_documento_por_usuario_y_tipo",
                    )
                ],
            },
        ),
    ]
