# Generated by Django 6.0.1 on 2026-02-14 00:00

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convocatorias", "0003_perfilusuario_documentousuario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="convocatoria",
            name="duracion_cita_minutos",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="Duracion de cada cita en minutos",
            ),
        ),
        migrations.AddField(
            model_name="convocatoria",
            name="hora_recepcion_fin",
            field=models.TimeField(
                default=datetime.time(14, 0),
                help_text="Hora de termino de recepcion documental",
            ),
        ),
        migrations.AddField(
            model_name="convocatoria",
            name="hora_recepcion_inicio",
            field=models.TimeField(
                default=datetime.time(9, 0),
                help_text="Hora de inicio de recepcion documental",
            ),
        ),
        migrations.AddField(
            model_name="convocatoria",
            name="personas_maximas_por_dia",
            field=models.PositiveIntegerField(
                default=80,
                help_text="Maximo de personas que se atenderan por dia",
            ),
        ),
        migrations.CreateModel(
            name="IntentoLoginTrabajador",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("username", models.CharField(max_length=150)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("intentos_fallidos", models.PositiveSmallIntegerField(default=0)),
                ("bloqueado_hasta", models.DateTimeField(blank=True, null=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("username", "ip"), name="uniq_intento_login_trabajador")
                ],
            },
        ),
        migrations.CreateModel(
            name="NotificacionUsuario",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("titulo", models.CharField(max_length=120)),
                ("mensaje", models.TextField()),
                ("leida", models.BooleanField(default=False)),
                ("fecha_creacion", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notificaciones_usuario",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"ordering": ["-fecha_creacion"]},
        ),
        migrations.CreateModel(
            name="SolicitudRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aceptada", "Aceptada"),
                            ("rechazada", "Rechazada"),
                            ("vencida", "Vencida"),
                        ],
                        default="pendiente",
                        max_length=20,
                    ),
                ),
                ("fecha_envio", models.DateTimeField(default=django.utils.timezone.now)),
                ("fecha_revision", models.DateTimeField(blank=True, null=True)),
                ("motivo_rechazo", models.TextField(blank=True)),
                ("plazo_correccion_limite", models.DateTimeField(blank=True, null=True)),
                ("fecha_cita", models.DateTimeField(blank=True, null=True)),
                ("numero_ficha", models.PositiveIntegerField(blank=True, null=True)),
                ("reenvios", models.PositiveIntegerField(default=0)),
                (
                    "inscripcion",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solicitud_revision",
                        to="convocatorias.inscripcion",
                    ),
                ),
                (
                    "revisado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="solicitudes_revisadas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="solicitudrevision",
            index=models.Index(fields=["estado", "fecha_envio"], name="convocatori_estado_4dad5a_idx"),
        ),
        migrations.AddIndex(
            model_name="solicitudrevision",
            index=models.Index(fields=["fecha_cita"], name="convocatori_fecha_c_d2da3f_idx"),
        ),
    ]
