# Generated by Django 6.0.1 on 2026-02-14 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("convocatorias", "0004_trabajador_flujo"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="solicitudrevision",
            name="area_asignada",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="solicitudrevision",
            name="trabajador_asignado",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="solicitudes_asignadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="TrabajadorPerfil",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("nombre_completo", models.CharField(max_length=255)),
                (
                    "area",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Area 1"),
                            (2, "Area 2"),
                            (3, "Area 3"),
                            (4, "Area 4"),
                            (5, "Area 5"),
                        ]
                    ),
                ),
                ("fecha_registro", models.DateField(auto_now_add=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="trabajador_perfil",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Perfil trabajador",
                "verbose_name_plural": "Perfiles trabajadores",
            },
        ),
    ]
