# Generated by Django 6.0.1 on 2026-02-14 01:00

from django.db import migrations


def quitar_staff_en_trabajadores(apps, schema_editor):
    User = apps.get_model("auth", "User")
    TrabajadorPerfil = apps.get_model("convocatorias", "TrabajadorPerfil")
    worker_user_ids = TrabajadorPerfil.objects.values_list("usuario_id", flat=True)
    User.objects.filter(id__in=worker_user_ids, is_superuser=False).update(is_staff=False)


class Migration(migrations.Migration):

    dependencies = [
        ("convocatorias", "0005_trabajadorperfil_asignacion"),
    ]

    operations = [
        migrations.RunPython(quitar_staff_en_trabajadores, migrations.RunPython.noop),
    ]
