# Generated by Django 6.0.1 on 2026-02-15 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0006_deshabilitar_staff_para_trabajadores'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='solicitudrevision',
            new_name='convocatori_estado_660ee2_idx',
            old_name='convocatori_estado_4dad5a_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitudrevision',
            new_name='convocatori_fecha_c_8436d1_idx',
            old_name='convocatori_fecha_c_d2da3f_idx',
        ),
    ]
