# Generated by Django 6.0.3 on 2026-04-09 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convocatorias', '0020_remove_convocatoriadocumentoconfiguracion_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresetcode',
            name='codigo_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='passwordresetcode',
            name='codigo',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
